site_name: Credit System - Flutter Frontend
site_description: Automated documentation for the Flutter credit system frontend
site_author: Credit System Team
site_url: https://yourusername.github.io/credit_system_flutter/
docs_dir: content
repo_name: credit_system/flutter_frontend
repo_url: https://github.com/yourusername/credit_system
theme:
  name: material
  features:
  - navigation.instant
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - search.highlight
  - search.share
  - content.code.copy
  - content.code.annotate
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-auto
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_source: true
          show_root_heading: true
          show_category_heading: true
          show_signature_annotations: true
          show_bases: true
          heading_level: 2
          members_order: source
          docstring_options:
            ignore_init_summary: true
- autorefs
nav:
- Home: index.md
- API Reference:
  - Managers: reference/managers.md
  - Widgets: reference/widgets.md
  - Services: reference/services.md
  - Modules: reference/modules.md
  - Utils: reference/utils.md
- Architecture:
  - Overview: architecture/overview.md
  - State Management: architecture/state-management.md
  - Authentication: architecture/auth.md
- Development:
  - Setup: development/setup.md
  - Testing: development/testing.md
  - Deployment: development/deployment.md
- API Documentation:
  - Overview: api/overview.md
markdown_extensions:
- admonition
- codehilite
- footnotes
- meta
- toc:
    permalink: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
