site_name: Credit System - Python Backend
site_description: Automated documentation for the Python credit system backend
site_author: Credit System Team
site_url: https://yourusername.github.io/credit_system_python/
docs_dir: content
repo_name: credit_system/python_backend
repo_url: https://github.com/yourusername/credit_system
theme:
  name: material
  features:
  - navigation.instant
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - search.highlight
  - search.share
  - content.code.copy
  - content.code.annotate
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-auto
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_source: true
          show_root_heading: true
          show_category_heading: true
          show_signature_annotations: true
          show_bases: true
          heading_level: 2
          members_order: source
          docstring_options:
            ignore_init_summary: true
        paths:
        - ../
- autorefs
nav:
- Home: index.md
- API Reference:
  - Managers: reference/managers.md
  - Modules: reference/modules.md
  - Services: reference/services.md
  - Utils: reference/utils.md
- Architecture:
  - Overview: architecture/overview.md
  - Data Flow: architecture/data-flow.md
  - Authentication: architecture/auth.md
- Development:
  - Setup: development/setup.md
  - Testing: development/testing.md
  - Deployment: development/deployment.md
- API Documentation:
  - Overview: api/overview.md
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/yourusername/credit_system
  - icon: fontawesome/brands/discord
    link: https://discord.gg/creditsystem
copyright: Copyright &copy; 2024 Credit System Team
