---
- name: Setup SSH Keys and User on remote
  hosts: rop01_initial
  become: true
  tasks:
    - name: Create user if not exists
      user:
        name: "{{ new_user }}"
        shell: /bin/bash
        create_home: yes
        state: present
        groups: sudo
        append: yes

    - name: Create .ssh directory
      file:
        path: "/home/{{ new_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ new_user }}"
        group: "{{ new_user }}"

    - name: Add SSH public key
      authorized_key:
        user: "{{ new_user }}"
        state: present
        key: "{{ ssh_keys_rop01 }}"
        key_options: 'no-port-forwarding,no-agent-forwarding,no-X11-forwarding'

    - name: Set up sudo access for new user
      lineinfile:
        path: "/etc/sudoers.d/{{ new_user }}"
        line: "{{ new_user }} ALL=(ALL) NOPASSWD: ALL"
        create: yes
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Display SSH setup complete message
      debug:
        msg: "SSH key setup complete. You can now SSH as {{ new_user }} using the rop01_key" 