---
- name: Setup WireGuard Client on Multipass
  hosts: rop02
  become: true
  vars:
    ansible_user: rop02_user
    ansible_ssh_private_key_file: /Users/sil/.ssh/rop02_key
    vault_server_public_key: "{{ lookup('file', '/Users/sil/Documents/Work/credit_system/app_dev/playbooks/vault_vps(rop01)/wireguard/values/server_public.txt') | trim }}"
    vault_server_ip: "{{ lookup('file', '/Users/sil/Documents/Work/credit_system/app_dev/playbooks/vault_vps(rop01)/wireguard/values/vault_ip.txt') | regex_replace(':.*$', '') }}"
    allowed_ips: "{{ lookup('file', '/Users/sil/Documents/Work/credit_system/app_dev/playbooks/vault_vps(rop01)/wireguard/values/vault_allowwed_ips.txt') | trim }}"
  tasks:
    - name: Install required packages
      apt:
        name: 
          - wireguard
          - netfilter-persistent
        state: present
        update_cache: yes

    - name: Create WireGuard directory
      file:
        path: /etc/wireguard
        state: directory
        mode: '0700'

    - name: Generate WireGuard client keys
      shell: |
        wg genkey | tee /etc/wireguard/client_private.key | wg pubkey | tee /etc/wireguard/client_public.key
      args:
        creates: /etc/wireguard/client_private.key

    - name: Get client public key
      slurp:
        src: /etc/wireguard/client_public.key
      register: client_public_key

    - name: Get client private key
      slurp:
        src: /etc/wireguard/client_private.key
      register: client_private_key

    - name: Create WireGuard client configuration
      copy:
        content: |
          [Interface]
          PrivateKey = {{ client_private_key.content | b64decode }}
          Address = 10.0.0.2/24
          SaveConfig = true

          [Peer]
          PublicKey = {{ vault_server_public_key }}
          Endpoint = {{ vault_server_ip }}:51820
          AllowedIPs = {{ allowed_ips }}
        dest: /etc/wireguard/wg0.conf
        mode: '0600'

    - name: Enable and start WireGuard service
      systemd:
        name: wg-quick@wg0
        state: started
        enabled: yes

    - name: Display client public key
      debug:
        msg: "Client public key: {{ client_public_key.content | b64decode }}"

    - name: Create local wireguard directory
      local_action:
        module: file
        path: "{{ playbook_dir }}/wireguard"
        state: directory
        mode: '0700'
      become: false

    - name: Create wireguard values directory
      local_action:
        module: file
        path: "{{ playbook_dir }}/wireguard/values"
        state: directory
        mode: '0700'
      become: false

    - name: Copy client public key to local wireguard directory
      local_action:
        module: copy
        content: "{{ client_public_key.content | b64decode }}"
        dest: "{{ playbook_dir }}/wireguard/values/client_public.txt"
        mode: '0600'
      become: false 