---
- name: Update Vault WireGuard Peers
  hosts: vault_private
  become: true
  vars:
    ansible_user: hcvlt
    ansible_ssh_private_key_file: /Users/sil/.ssh/vault_key
    wg_config_path: /etc/wireguard/wg0.conf
    rop02_public_key: "{{ lookup('file', '/Users/sil/Documents/Work/credit_system/app_dev/playbooks/rop02/wireguard/values/client_public.txt') | trim }}"
    rop02_ip: 10.0.0.2/32
  tasks:
    - name: Temporarily disable SaveConfig
      replace:
        path: "{{ wg_config_path }}"
        regexp: '^SaveConfig = true'
        replace: 'SaveConfig = false'

    - name: Add new peer to WireGuard configuration
      shell: |
        echo '\n[Peer]\nPublicKey = {{ rop02_public_key }}\nAllowedIPs = {{ rop02_ip }}' | sudo tee -a {{ wg_config_path }}

    - name: Re-enable SaveConfig
      replace:
        path: "{{ wg_config_path }}"
        regexp: '^SaveConfig = false'
        replace: 'SaveConfig = true'

    - name: Manual restart instructions
      debug:
        msg: |
          Please manually restart WireGuard on the Vault server with:
            sudo systemctl restart wg-quick@wg0
          or, if on macOS:
            sudo wg-quick down wg0 && sudo wg-quick up wg0
          Then verify with:
            sudo wg show 