version: '3.8'

services:
  flask-app:
    build: ./python_base_04_k8s
    ports:
      - "8080:5001"
    volumes:
      - ./python_base_04_k8s:/app
      - ./python_base_04_k8s/tools/logger:/app/tools/logger
    environment:
      - MONGODB_URI=mongodb://localhost:27017
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_PASSWORD=7cNfJTOcyDxdhK5NZubMoE7KS
      - MONGODB_HOST=localhost
      - MONGODB_PORT=27017
      - MONGODB_ROOT_PASSWORD=rootpassword
      - MONGODB_USER=credit_system_user
      - MONGODB_PASSWORD=credit_system_password
      - MONGODB_DB_NAME=credit_system
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 