---
- name: Setup Database Structure for Credit System (Local k3d)
  hosts: localhost
  connection: local
  vars:
    flask_namespace: "flask-app"
    mongodb_service: "mongodb"
    database_name: "credit_system"
    app_username: "credit_app_user"
    app_password: "6R3jjsvVhIRP20zMiHdkBzNKx"
    
    # Root user credentials (created by Helm)
    root_username: "mongodb_admin"
    root_password: "MongoAdmin123!@#SecurePass"
    
    # MongoDB connection details
    mongodb_host: "{{ mongodb_service }}.{{ flask_namespace }}.svc.cluster.local"
    mongodb_port: "27017"
    mongodb_auth_source: "{{ database_name }}"
    
    # Collections to create
    collections:
      - name: "users"
        module: "User Management"
        indexes:
          - key: {"email": 1}
            unique: true
            name: "email_unique"
          - key: {"username": 1}
            unique: true
            name: "username_unique"
          - key: {"status": 1}
            name: "status_index"
          - key: {"created_at": 1}
            name: "created_at_index"
      
      - name: "wallets"
        module: "Wallet"
        indexes:
          - key: {"user_id": 1}
            unique: true
            name: "user_id_unique"
          - key: {"balance": 1}
            name: "balance_index"
          - key: {"updated_at": 1}
            name: "updated_at_index"
      
      - name: "transactions"
        module: "Transactions"
        indexes:
          - key: {"user_id": 1}
            name: "user_id_index"
          - key: {"type": 1}
            name: "type_index"
          - key: {"timestamp": 1}
            name: "timestamp_index"
          - key: {"user_id": 1, "timestamp": -1}
            name: "user_timestamp_index"
          - key: {"ref_id": 1}
            name: "ref_id_index"
      
      - name: "purchases"
        module: "Purchases"
        indexes:
          - key: {"user_id": 1}
            name: "user_id_index"
          - key: {"provider": 1}
            name: "provider_index"
          - key: {"status": 1}
            name: "status_index"
          - key: {"created_at": 1}
            name: "created_at_index"
          - key: {"user_id": 1, "created_at": -1}
            name: "user_created_index"
      
      - name: "payment_providers"
        module: "Payments"
        indexes:
          - key: {"user_id": 1}
            name: "user_id_index"
          - key: {"provider": 1}
            name: "provider_index"
          - key: {"purchase_token": 1}
            unique: true
            name: "purchase_token_unique"
          - key: {"linked_purchase_id": 1}
            name: "linked_purchase_index"
          - key: {"status": 1}
            name: "status_index"
          - key: {"validated_at": 1}
            name: "validated_at_index"
      
      - name: "audit_logs"
        module: "Audit/Admin"
        indexes:
          - key: {"user_id": 1}
            name: "user_id_index"
          - key: {"action": 1}
            name: "action_index"
          - key: {"admin_id": 1}
            name: "admin_id_index"
          - key: {"timestamp": 1}
            name: "timestamp_index"
          - key: {"user_id": 1, "timestamp": -1}
            name: "user_timestamp_index"

  tasks:
    - name: Verify MongoDB is running
      shell: |
        kubectl get pods -n {{ flask_namespace }} -l app.kubernetes.io/name=mongodb --no-headers | grep Running
      register: mongodb_pod_status
      changed_when: false
      failed_when: mongodb_pod_status.rc != 0

    - name: Wait for MongoDB to be ready
      shell: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=mongodb -n {{ flask_namespace }} --timeout=60s
      changed_when: false

    - name: Drop and recreate database completely
      shell: |
        echo "🗑️  Dropping entire database..."
        kubectl exec -n {{ flask_namespace }} deployment/{{ mongodb_service }} -- \
          mongosh "mongodb://{{ app_username }}:{{ app_password }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ database_name }}?authSource={{ mongodb_auth_source }}" \
          --eval "
            print('🗑️  Dropping database: {{ database_name }}');
            db = db.getSiblingDB('{{ database_name }}');
            db.dropDatabase();
            print('✅ Database dropped successfully');
          "
      ignore_errors: true

    - name: Wait for database drop to complete
      shell: sleep 2
      changed_when: false

    - name: Create collections
      shell: |
        echo "📋 Creating collections..."
        kubectl exec -n {{ flask_namespace }} deployment/{{ mongodb_service }} -- \
          mongosh "mongodb://{{ app_username }}:{{ app_password }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ database_name }}?authSource={{ mongodb_auth_source }}" \
          --eval "
            use {{ database_name }};
            const collections = ['users', 'wallets', 'transactions', 'purchases', 'payment_providers', 'audit_logs'];
            collections.forEach(function(collection) {
              if (!db.getCollectionNames().includes(collection)) {
                db.createCollection(collection);
                print('✅ Created collection: ' + collection);
              } else {
                print('ℹ️  Collection exists: ' + collection);
              }
            });
          "
      ignore_errors: true

    - name: Create users indexes
      shell: |
        echo "🔍 Creating users indexes..."
        kubectl exec -n {{ flask_namespace }} deployment/{{ mongodb_service }} -- \
          mongosh "mongodb://{{ app_username }}:{{ app_password }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ database_name }}?authSource={{ mongodb_auth_source }}" \
          --eval "
            use {{ database_name }};
            try { db.users.createIndex({email: 1}, {unique: true, name: 'email_unique'}); print('✅ email_unique'); } catch(e) { if (e.code === 85) print('ℹ️  email_unique exists'); }
            try { db.users.createIndex({username: 1}, {unique: true, name: 'username_unique'}); print('✅ username_unique'); } catch(e) { if (e.code === 85) print('ℹ️  username_unique exists'); }
            try { db.users.createIndex({status: 1}, {name: 'status_index'}); print('✅ status_index'); } catch(e) { if (e.code === 85) print('ℹ️  status_index exists'); }
          "
      ignore_errors: true

    - name: Create wallets indexes
      shell: |
        echo "🔍 Creating wallets indexes..."
        kubectl exec -n {{ flask_namespace }} deployment/{{ mongodb_service }} -- \
          mongosh "mongodb://{{ app_username }}:{{ app_password }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ database_name }}?authSource={{ mongodb_auth_source }}" \
          --eval "
            use {{ database_name }};
            try { db.wallets.createIndex({user_id: 1}, {unique: true, name: 'user_id_unique'}); print('✅ user_id_unique'); } catch(e) { if (e.code === 85) print('ℹ️  user_id_unique exists'); }
            try { db.wallets.createIndex({balance: 1}, {name: 'balance_index'}); print('✅ balance_index'); } catch(e) { if (e.code === 85) print('ℹ️  balance_index exists'); }
          "
      ignore_errors: true

    - name: Create transactions indexes
      shell: |
        echo "🔍 Creating transactions indexes..."
        kubectl exec -n {{ flask_namespace }} deployment/{{ mongodb_service }} -- \
          mongosh "mongodb://{{ app_username }}:{{ app_password }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ database_name }}?authSource={{ mongodb_auth_source }}" \
          --eval "
            use {{ database_name }};
            try { db.transactions.createIndex({user_id: 1}, {name: 'user_id_index'}); print('✅ user_id_index'); } catch(e) { if (e.code === 85) print('ℹ️  user_id_index exists'); }
            try { db.transactions.createIndex({type: 1}, {name: 'type_index'}); print('✅ type_index'); } catch(e) { if (e.code === 85) print('ℹ️  type_index exists'); }
            try { db.transactions.createIndex({timestamp: 1}, {name: 'timestamp_index'}); print('✅ timestamp_index'); } catch(e) { if (e.code === 85) print('ℹ️  timestamp_index exists'); }
          "
      ignore_errors: true

    - name: Create purchases indexes
      shell: |
        echo "🔍 Creating purchases indexes..."
        kubectl exec -n {{ flask_namespace }} deployment/{{ mongodb_service }} -- \
          mongosh "mongodb://{{ app_username }}:{{ app_password }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ database_name }}?authSource={{ mongodb_auth_source }}" \
          --eval "
            use {{ database_name }};
            try { db.purchases.createIndex({user_id: 1}, {name: 'user_id_index'}); print('✅ user_id_index'); } catch(e) { if (e.code === 85) print('ℹ️  user_id_index exists'); }
            try { db.purchases.createIndex({provider: 1}, {name: 'provider_index'}); print('✅ provider_index'); } catch(e) { if (e.code === 85) print('ℹ️  provider_index exists'); }
            try { db.purchases.createIndex({status: 1}, {name: 'status_index'}); print('✅ status_index'); } catch(e) { if (e.code === 85) print('ℹ️  status_index exists'); }
          "
      ignore_errors: true

    - name: Create payment_providers indexes
      shell: |
        echo "🔍 Creating payment_providers indexes..."
        kubectl exec -n {{ flask_namespace }} deployment/{{ mongodb_service }} -- \
          mongosh "mongodb://{{ app_username }}:{{ app_password }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ database_name }}?authSource={{ mongodb_auth_source }}" \
          --eval "
            use {{ database_name }};
            try { db.payment_providers.createIndex({user_id: 1}, {name: 'user_id_index'}); print('✅ user_id_index'); } catch(e) { if (e.code === 85) print('ℹ️  user_id_index exists'); }
            try { db.payment_providers.createIndex({purchase_token: 1}, {unique: true, name: 'purchase_token_unique'}); print('✅ purchase_token_unique'); } catch(e) { if (e.code === 85) print('ℹ️  purchase_token_unique exists'); }
          "
      ignore_errors: true

    - name: Create audit_logs indexes
      shell: |
        echo "🔍 Creating audit_logs indexes..."
        kubectl exec -n {{ flask_namespace }} deployment/{{ mongodb_service }} -- \
          mongosh "mongodb://{{ app_username }}:{{ app_password }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ database_name }}?authSource={{ mongodb_auth_source }}" \
          --eval "
            use {{ database_name }};
            try { db.audit_logs.createIndex({user_id: 1}, {name: 'user_id_index'}); print('✅ user_id_index'); } catch(e) { if (e.code === 85) print('ℹ️  user_id_index exists'); }
            try { db.audit_logs.createIndex({action: 1}, {name: 'action_index'}); print('✅ action_index'); } catch(e) { if (e.code === 85) print('ℹ️  action_index exists'); }
            try { db.audit_logs.createIndex({timestamp: 1}, {name: 'timestamp_index'}); print('✅ timestamp_index'); } catch(e) { if (e.code === 85) print('ℹ️  timestamp_index exists'); }
          "
      ignore_errors: true
      register: db_setup_result
      changed_when: true

    - name: Verify database structure
      shell: |
        echo "🔍 Verifying database structure..."
        kubectl exec -n {{ flask_namespace }} deployment/{{ mongodb_service }} -- \
          mongosh "mongodb://{{ app_username }}:{{ app_password }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ database_name }}?authSource={{ mongodb_auth_source }}" \
          --eval "
            use {{ database_name }};
            print('📋 Collections: ' + db.getCollectionNames().join(', '));
            print('✅ Database structure verified');
          "
      register: db_verification
      changed_when: false
      ignore_errors: true

    - name: Display database setup summary
      debug:
        msg: |
          🗄️ Credit System Database Structure Setup Complete!
          
          📋 Modular Database Design:
          - users (User Management Module)
          - wallets (Wallet Module) 
          - transactions (Transactions Module)
          - purchases (Purchases Module)
          - payment_providers (Payments Module)
          - audit_logs (Audit/Admin Module)
          
          🔗 Connection Details:
          - Host: {{ mongodb_host }}
          - Port: {{ mongodb_port }}
          - Database: {{ database_name }}
          - User: {{ app_username }}
          - Auth Source: {{ mongodb_auth_source }}
          
          🧪 Test Credentials:
          - Email: test@example.com
          - Username: testuser
          - Password: password123
          - Balance: 1000 credits
          
          📊 Database Verification:
          {{ db_verification.stdout }}
          
          ✅ Database structure is ready for development!

    - name: Display connection string for applications
      debug:
        msg: |
          🔗 MongoDB Connection String for Applications:
          
          mongodb://{{ app_username }}:{{ app_password }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ database_name }}?authSource={{ mongodb_auth_source }}
          
          📝 Environment Variables:
          MONGODB_URI=mongodb://{{ app_username }}:{{ app_password }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ database_name }}?authSource={{ mongodb_auth_source }}
          MONGODB_DATABASE={{ database_name }}
          MONGODB_USER={{ app_username }}
          MONGODB_PASSWORD={{ app_password }} 