---
- name: Set up K3s and Kubernetes Access
  hosts: vault_public
  become: true
  vars:
    k3s_user: hcvlt  # Updated to match the user in inventory.ini
    ansible_user: hcvlt
    ansible_ssh_private_key_file: /Users/sil/.ssh/vault_key

  tasks:
    - name: Install K3s
      shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Verify K3s Installation
      service:
        name: k3s
        state: started
        enabled: yes

    - name: Create .kube directory
      file:
        path: /home/{{ k3s_user }}/.kube
        state: directory
        owner: "{{ k3s_user }}"
        group: "{{ k3s_user }}"
        mode: '0700'

    - name: Fetch the Kubeconfig File
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/{{ k3s_user }}/.kube/config
        remote_src: yes
        owner: "{{ k3s_user }}"
        group: "{{ k3s_user }}"
        mode: '0600'

    - name: Set the KUBECONFIG Environment Variable
      lineinfile:
        path: /home/{{ k3s_user }}/.bashrc
        line: 'export KUBECONFIG=/home/{{ k3s_user }}/.kube/config'
        state: present

    - name: Source .bashrc
      shell: . /home/{{ k3s_user }}/.bashrc
      args:
        executable: /bin/bash

    - name: Create kubectl symlink
      file:
        src: /usr/local/bin/k3s
        dest: /usr/local/bin/kubectl
        state: link
        force: yes 